# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: Build and deploy Python project to Azure Function App - user-auth

on:
  push:
    branches:
      - main
    paths:
      - "user-auth/**"
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "user-auth" # set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: "3.12" # set this to the python version to use (supports 3.6, 3.7, 3.8)

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Validate project layout
        run: ls -R ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
  
      - name: Zip artifact for deployment
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          zip -r ../release.zip ./* \
              --exclude "venv/*" \
              --exclude ".venv/*"
  
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6F92FDE6D92A43BC883FB364567BCD26 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C92A7E30E76A4099A43840434B60920F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0633B6C4EF674C47A1CA1939E81AFF4C }}

      - name: "Deploy to Azure Functions"
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: "user-auth"
          slot-name: "Production"
          package: .
